### ISSUE TITLE
Names used in reverse (url tags in templates) and url config don't match

### ISSUE THREAD

**Issue by atleta** [cdelguercio/slothauth#2]
Hi,

The templates use url names with an 'account-' prefix (e.g. account-login, account-logout, etc), while the url config misses these prefixes, so none of the pages actually work without overriding the templates.

**Comment by atleta** [comment]
Hmm... OK, so it seems that you don't provide views for logging in (i.e. processing the form posts). Still, the documentation could be more clear about how to do this and mention that login views will break without the necessary urls.

**Comment by cdelguercio** [comment]
I do provide views for logging in. Let me check out what the problem is and get back to you.

**Comment by cdelguercio** [comment]
Ah, they only work if you name your user model "Account". I really should rewrite the templates so that they work no matter what your user model is called, but for now you can name it Account and it should work. Also note that I added that you need to include 'rest_framework' and 'rest_framework.authtoken' in your INSTALLED_APPS to the README.

**Comment by atleta** [comment]
I have the apps in INSTALLED_APPS. Not sure where those views are, though. I mean I see the API views but I was talking about plain, html serving ones. Which you seem not to provide. (Also, as far as I can see, your views will work with any user model, because you, correctly, use the get_user_model function at the top of views.py)

**Comment by cdelguercio** [comment]
They are right here: https://github.com/cdelguercio/slothauth/blob/master/slothauth/views.py#L181

The problem is that I reference the API views as account-signup, account-login, etc. Django Rest Framework and Django's class based view system builds the string url alias in the form of <model_name>-<view_name> so my templates will only reference the correct urls if you name your user model "Account" instead of "User". These urls are only suppose to give you quick use of Slothauth and aren't meant for production at all (They even turn off if DEBUG=False), so you're probably better off just making your own templates and referencing the API endpoints with action="{% url '<your_lowercase_user_model_name>-login' %}"

**Comment by atleta** [comment]
These aren't fully functioning views, they just return the templates. My original question was if there were views that process the form posts. But the answer seems to be no. So the purpose of this app seems to be to provide authentication through a REST API. Correct? (I'm just trying to make an app work that uses it. And I need standard, form post based, non-API logins as well.) I'm aware that the API endpoints can process the form posts, but can't respond with an HTML template.

**Comment by cdelguercio** [comment]
I'm sorry, I didn't understand. Yes, SlothAuth only has REST API style endpoints. You are meant to do all of your form submission and redirecting via JavaScript. I recommend using React or Angular 2.

**Comment by atleta** [comment]
OK, np. Thanks for the clarification.
